name: Build and Publish Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract Docker tag from Git tag
      id: extract_tag
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: itmpsk/cronicle:${{ env.TAG }}

    - name: Update Docker Hub README
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REPO: itmpsk/cronicle
      run: |
        echo "Updating Docker Hub README"
        README_CONTENT=$(cat README.md)
        TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'"$DOCKER_USERNAME"'", "password": "'"$DOCKER_PASSWORD"'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
        curl -s -H "Authorization: JWT $TOKEN" -H "Content-Type: application/json" -X PATCH -d '{"full_description": "'"${README_CONTENT//\"/\\\"}"'"}' https://hub.docker.com/v2/repositories/$DOCKER_REPO/

    - name: Log out from Docker Hub
      run: docker logout